version: 2.1
orbs: 
  node: circleci/node@5.0.2

jobs:
  1-test:
    executor:
      name: node/default
      tag: '16.15.0'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          command: yarn run test
          name: Run YARN tests
      - store_test_results:
          path: junit.xml
      
  2-lint:
    executor:
      name: node/default
      tag: '16.15.0'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          command: yarn run lint
          name: Run YARN eslint
  3-build:
    executor:
      name: node/default
      tag: '16.15.0'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          command: yarn run build
          name: Run YARN build
  4-deploy:
    executor:
      name: node/default
      tag: '16.15.0'
    steps:
      - checkout      
      - run:
          name: Publish to NPM
          command: |
            npm set //registry.npmjs.org/:_authToken=$npm_TOKEN
            npm publish


 

workflows:
  version: 2
  build_and_test: 
    jobs:
      - 1-test
      - 2-lint
      - 3-build
      - 4-deploy
