version: 2.1
orbs: 
  node: circleci/node@5.0.2

jobs:
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          command: yarn run test
          name: Run YARN tests
      - store_test_results:
          path: junit.xml
      
  lint:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn-berry
      - run:
          command: yarn run lint
          name: Run YARN eslint
  deploy:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/pptx-renderer/.npmrc
      - run:
          name: Publish package
          command: npm publish


 

workflows:
  version: 2
  build_and_test: 
    jobs:
      - test
      - lint
      - deploy
