version: 2.1
orbs: 
  node: circleci/node@5.0.2

jobs:         
  test:    
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          command: yarn run test
          name: Run YARN tests
      - store_test_results:
          path: junit.xml
      
  lint:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node --version
      - run:
          command: yarn run lint
          name: Run YARN eslint
  deploy:
    executor:
      name: node/default
      tag: '16.13'
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/pptx-renderer/.npmrc
      - run:
          name: Publish package
          command: npm publish


 

workflows:
  version: 2
  build_and_test: 
    jobs:
      - test
      - lint
      - deploy
