version: 2.1
orbs: 
  node: circleci/node@5.0.0

jobs:         
  test:
    executor:
      name: node/default
      tag: '17.3.1'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: true
      - run:
          command: yarn run test
          name: Run YARN tests
      - store_artifacts:
          path: coverage
      
  lint:
    executor:
      name: node/default
      tag: '17.3.1'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: true
      - run:
          command: yarn run lint
          name: Run YARN eslint


 

workflows:
  version: 2
  build_and_test: 
    jobs:
      - test
      - lint
