version: 2.1
orbs: 
  node: circleci/node@5.0.0
aliases:
  - &restore-yarn-cache
    restore_cache:
      name: Restore yarn cache
      key: v2-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn

  - &save-yarn-cache
    # Store the yarn cache globally for all lock files with this same
    # checksum. This will speed up the setup job for all PRs where the
    # lockfile is the same.
    name: Save yarn cache for future installs
    key: v2-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn
    paths:
      - ~/.cache/yarn
      

  - &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      keys:
        - v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "workspace_info.txt" }}-node-modules

   

executors:
  node-executor:
    docker:
      - image: cimg/node:17.3.1
    working_directory: ~/pptx-renderer
   

jobs:
  setup:
    executor: node-executor
    steps:
      - checkout
      - run:
            name: Nodejs Version
            command: node --version
      - *restore-yarn-cache
      - run:
          name: Install Packages
          command: yarn install --immutable
      - run: yarn workspaces info | head -n -1 > workspace_info.txt
      - save_cache: *save-yarn-cache 
      - save_cache:
          # Store node_modules for all jobs in this workflow so that they don't
          # need to each run a yarn install for each job. This will speed up
          # all jobs run on this branch with the same lockfile.
          name: Save node_modules cache
          # This cache key is per branch, a yarn install in setup is required.
          key: v2-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-{{ checksum "workspace_info.txt" }}-node-modules
          paths:
            - node_modules
         
  test:
    executor:
      name: node/default
      tag: '16'
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          command: yarn run test
          name: Run YARN tests
      
  eslint:
     executor: node-executor
     steps:
      - checkout
      - run: yarn workspaces info | head -n -1 > workspace_info.txt
      - *restore_node_modules
      - run: yarn lint


 

workflows:
  version: 2
  build_and_test: 
    jobs:
      - setup
      - eslint:
          requires:
            - setup
      - test:
          requires:
            - setup
